version: '3'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 VC.asgi:application
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ALLOWED_HOSTS=0.0.0.0,localhost,127.0.0.1
      - DJANGO_SETTINGS_MODULE=VC.settings
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
