# Generated by Django 5.0.3 on 2024-04-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_txt',
        ),
    ]
