# Generated by Django 5.0.3 on 2024-04-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0003_rename_test_test_txt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_txt',
        ),
    ]
