# Generated by Django 5.0.3 on 2024-04-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_weather', models.CharField(max_length=100)),
                ('day_weather', models.CharField(max_length=100)),
                ('evening_weather', models.CharField(max_length=100)),
                ('current_weather', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.city')),
            ],
        ),
    ]
